version: "3.7"

volumes:
  pubsub_data:

services:
  pubsub:
    image: vovimayhem/google-pubsub-emulator:latest
    ports:
      - ${DEMO_PUBSUB_PORT:-8085}:8085
    volumes:
      - pubsub_data:/data