apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "gcp-docker-task-runner-poc-config"
  namespace: "default"
data:
  GOOGLE_CLOUD_PROJECT_ID: "vovi-playground-235816"
  GOOGLE_CLOUD_PUBSUB_TOPIC: "example-pubsub-topic"
  GOOGLE_CLOUD_PUBSUB_SUBSCRIPTION: "example-pubsub-subscription"
  DEMO_GOOGLE_CLOUD_KEYFILE_PATH: "/etc/secrets/service-account-key"